name: Daily Scheduled Task

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 2:00 (UTC)
  workflow_dispatch:      # 也支持手动触发

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build china jar
        run: |
          ./gradlew clean build
      - name: package sqlite
        run: |
          today=$(date '+%Y-%m-%d-%H-%M')
          db_file="${today}.db"
          echo "buildTime=$today" >> $GITHUB_ENV
          echo "db_path=${{github.workspace}}/$db_file" >> $GITHUB_ENV
          echo ${{env.buildTime}}
          echo ${{env.db_path}}
          java -jar ${{github.workspace}}/build/libs/subsonic_database_scan-1.0-SNAPSHOT.jar ${{ secrets.host }} ${{ secrets.user }} ${{ secrets.password }} ${{ env.db_path }}
      - name: Create Release
        id: create_remote_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{env.buildTime}}
          tag_name: ${{env.buildTime}}
          files: ${{ env.db_path }}