name: Daily Scheduled Task

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 2:00 (UTC)
  workflow_dispatch:      # 也支持手动触发

jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 18
        uses: actions/setup-java@v3
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build china jar
        run: |
          ./gradlew clean build
      - name: package sqlite
        run: |
          today=$(date '+%Y-%m-%d-%H-%M')
          host=$(echo "${{ secrets.host }}" | sed -E 's#^https?://([^/:]+).*#\1#' | sed 's/\./_/g')
          echo "$host"
          db_file="main.db"
          echo "buildTime=$today" >> $GITHUB_ENV
          db_path=${{github.workspace}}/$db_file
          echo "db_path=${{github.workspace}}/$db_file" >> $GITHUB_ENV
          echo $db_path
          echo "${{ secrets.host }} ${{ secrets.user }} ${{ secrets.password }}"
          java -jar ${{github.workspace}}/build/libs/subsonic_database_scan-1.0-SNAPSHOT.jar 1 ${{ secrets.host }} ${{ secrets.user }} ${{ secrets.password }} $db_path
          zipFile="$host.db.zip"
          echo "zipFile=$zipFile" >> $GITHUB_ENV
          cd ${{github.workspace}}
          zip $zipFile $db_file
      - name: Create Release
        id: create_remote_release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{env.buildTime}}
          tag_name: ${{env.buildTime}}
          files: ${{ env.db_path }}.zip